import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :apm, ApmWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :apm, ApmWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  exclude: [
    # paths: ["/health"],
    hosts: ["localhost", "127.0.0.1", "[::1]"]
  ]

# Do not print debug messages in production
config :logger, level: :info

# --- v9.3.0 Audit: structured JSON logging (audit-s5 / CP-223) ---
# In production, replace the default text formatter with LoggerJSON ECS output.
# `agent_id`, `session_id`, and `formation_id` are emitted automatically when
# set via `Logger.metadata/1` (e.g. in session_init or APM session start).
config :logger, :default_handler,
  formatter:
    {LoggerJSON.Formatters.Elastic,
     metadata: [:agent_id, :session_id, :formation_id, :request_id, :remote_ip]}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
