defmodule ApmWeb.Endpoint do
  @moduledoc """
  Phoenix Endpoint for the APM web application.

  Configures static file serving, session management, LiveView socket,
  and the Bandit HTTP/WebSocket adapter.
  """

  use Phoenix.Endpoint, otp_app: :apm

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_apm_key",
    signing_salt: "qh4edlt0",
    same_site: "Lax"
  ]

  socket "/socket", ApmWeb.UserSocket,
    websocket: true,
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [session: @session_options],
      check_origin: false,
      timeout: 60_000
    ],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :apm,
    gzip: not code_reloading?,
    only: ApmWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Cache the OpenAPI spec at startup so CastAndValidate can introspect it.
  # Wave 1 (CP-228): no paths are annotated yet, so CastAndValidate is a
  # no-op for all existing routes. Annotation migrates incrementally in Wave 2
  # (api-s5 / api-s7). See ApmWeb.ApiSpec for details.
  plug OpenApiSpex.Plug.PutApiSpec, module: ApmWeb.ApiSpec

  plug ApmWeb.Router
end
